version: '{build}'

platform:
  - x86
  - x64

image:
  - Visual Studio 2015
  - Visual Studio 2017

build_script:
  - if "%PLATFORM%" == "x64" (set ARCH=_x64) else (set ARCH= )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" (set VSY=2017) else (set VSY=2015)
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%" == "Visual Studio 2017" (set VSTS=v141) else (set VSTS=v140)
  - pushd ide
  - configure_VS%VSY%%ARCH%.cmd
  - echo VS%VSY%_%VSTS%%ARCH%
  - pushd VS%VSY%_%VSTS%%ARCH%
  - cmake --build . --config Release -- /M
