dist: trusty
sudo: require
language: c
compiler: gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-5
      - cmake
script:
  - sudo ln -s /usr/bin/gcc-5 /usr/local/bin/gcc
  - export CC=/usr/bin/gcc-5
  - mkdir cmake-build
  - cd cmake-build
  - cmake ..
  - cmake --build .
